ProfileScreen
salvadorkano/redTec pull request #5
Opened 2023-10-19 23:06 UTC by RogerPerva

Profile Screen, please advise.

2023-10-19 23:40 UTC, RogerPerva commented
![Imagen 19-10-23 a las 5 38 p m](https://github.com/salvadorkano/redTec/assets/108033058/ac9afe9b-6acd-4485-b8bd-4d5602e6741f)

2023-10-21 23:50 UTC, salvadorkano requested changes

2023-10-21 23:50 UTC, salvadorkano commented on src/router/authStack.tsx
En el Stack del login no debería ir el Profile

2023-10-21 23:50 UTC, salvadorkano commented on README.md
Elimina esto si no se usara

2023-10-21 23:50 UTC, salvadorkano commented on src/assets/images/smallLogo.png
Verifica si ese logo no existia en el proyecto porque creo que ya existiay se usaba en el Login

2023-10-24 20:14 UTC, merged